// Launch the app from source, open a demo folder on the Library page, screenshot grid/list/preview.
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const ROOT = "C:\\Project Folder\\Unpacker V2";
const { _electron } = require(path.join(ROOT, "docs", "_tools", "node_modules", "playwright-core"));
const ELECTRON = require(path.join(ROOT, "node_modules", "electron"));
const OUT = path.join(__dirname, "shots");
fs.mkdirSync(OUT, { recursive: true });

const demo = path.join(os.tmpdir(), "unp-lib-demo");
fs.rmSync(demo, { recursive: true, force: true });
const mk = (rel, data) => { const p = path.join(demo, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, data); };
const shots = fs.readdirSync(path.join(ROOT, "docs/screenshots")).filter((n) => n.endsWith(".png"));
shots.forEach((n, i) => mk(`Memories/2024/${String((i % 3) + 1).padStart(2, "0")}/2024-0${(i % 3) + 1}-1${i}_12${i}000.png`, fs.readFileSync(path.join(ROOT, "docs/screenshots", n))));
mk("Memories/index.csv", "file,taken,latitude,longitude\r\n" + shots.map((n, i) => `2024-0${(i % 3) + 1}-1${i}_12${i}000.png,2024-0${(i % 3) + 1}-1${i} 12:${i}0:00,41.5,-81.6`).join("\r\n") + "\r\n");
mk("Chats/pal/Chat with pal.txt", "Chat with pal\n2 messages\n\n2024-01-02 10:00:00  pal: hi there\n2024-01-02 10:01:00  me: hey\n");
mk("Account data/account.txt", "Basic Information:\n  Username: demo\n");
mk("Snapchat library report.txt", "Snapchat library\nmemories: 9 placed\nchats: 1\n");
mk("What's in here.txt", "Snapchat Library\n  Memories/  9 photos\n  Chats/     1 conversation\n  Account data/\n");

(async () => {
  const profile = path.join(os.tmpdir(), "unp-lib-profile");
  const app = await _electron.launch({ executablePath: ELECTRON, args: [path.join(ROOT, "src/main/main.js"), "--dev", `--user-data-dir=${profile}`], cwd: ROOT });
  const page = await app.firstWindow();
  const errors = [];
  page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
  page.on("pageerror", (e) => errors.push("PAGEERROR " + e.message));
  await page.waitForLoadState("domcontentloaded");
  await page.waitForTimeout(800);
  await page.setViewportSize({ width: 1280, height: 780 });
  await page.evaluate((d) => window.libraryTab.openFolder(d), demo);
  await page.waitForTimeout(900);
  await page.screenshot({ path: path.join(OUT, "lib-root.png") });
  await page.click(".li.dir:has-text('Memories')");
  await page.waitForTimeout(600);
  await page.click(".li.dir:has-text('2024')");
  await page.waitForTimeout(500);
  await page.click(".li.dir:has-text('01')");
  await page.waitForTimeout(1200);
  await page.click(".li:not(.dir)");
  await page.waitForTimeout(900);
  await page.screenshot({ path: path.join(OUT, "lib-photo.png") });
  const thumbs = await page.evaluate(() => [...document.querySelectorAll(".li-thumb img")].map((i) => i.naturalWidth));
  console.log("thumb widths:", thumbs.join(","));
  await page.click("#libView button[data-view=list]");
  await page.waitForTimeout(400);
  await page.evaluate((d) => window.libraryTab.openFolder(d), demo);
  await page.waitForTimeout(500);
  await page.fill("#libSearch", "csv");
  await page.waitForTimeout(700);
  await page.click(".li:not(.dir)");
  await page.waitForTimeout(700);
  await page.screenshot({ path: path.join(OUT, "lib-csv-list.png") });
  await page.fill("#libSearch", "");
  await page.waitForTimeout(500);
  await page.click(".li.dir:has-text('Chats')");
  await page.waitForTimeout(400);
  await page.click(".li.dir:has-text('pal')");
  await page.waitForTimeout(400);
  await page.click(".li:not(.dir)");
  await page.waitForTimeout(600);
  await page.screenshot({ path: path.join(OUT, "lib-chat.png") });
  console.log("console errors:", errors.length ? errors : "none");
  await app.close();
})().catch((e) => { console.error("CRASH", e); process.exit(2); });
